# XAUUSD (黄金) 品种配置

symbol: "XAUUSD"
spread_limit: 5.0
min_lot: 0.01
max_lot: 5.0
lot_step: 0.01
risk_multiplier: 0.8  # 黄金波动大，降低风险倍数

# 启用的策略
strategies:
  - "breakout"
  - "support_resistance"
  - "volatility_breakout"

# 支持的时间周期
timeframes:
  - "M5"
  - "M15"
  - "H1"
  - "H4"
  - "D1"

# 交易时间 (UTC) - 避开亚洲盘低波动时段
trading_hours:
  monday: "07:00-23:59"
  tuesday: "00:00-23:59"
  wednesday: "00:00-23:59"
  thursday: "00:00-23:59"
  friday: "00:00-21:00"

# 策略参数优化范围
optimize_params:
  bb_period: [15, 25, 5]
  bb_deviation: [1.5, 2.5, 0.5]
  atr_period: [10, 20, 5]
  atr_multiplier: [1.5, 3.0, 0.5]
  rsi_period: [12, 18, 2]
  support_resistance_lookback: [20, 50, 10]

# 风险参数
risk_params:
  max_spread: 8.0
  min_equity: 2000.0
  max_slippage: 5
  stop_loss_pips: 100   # 黄金点值大，用更大的止损
  take_profit_pips: 200

# 特殊事件监控
event_monitoring:
  - "FOMC"
  - "NFP"
  - "CPI"
  - "GDP"
  - "央行利率决议"